# Generated by Django 5.2.6 on 2025-10-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miappeva', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenvoz',
            options={},
        ),
        migrations.RenameField(
            model_name='ordenvoz',
            old_name='fecha',
            new_name='creado',
        ),
        migrations.AddField(
            model_name='ordenvoz',
            name='intent',
            field=models.CharField(default='desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='ordenvoz',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ordenvoz',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
