# Generated by Django 5.2.6 on 2025-10-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miappeva', '0002_alter_ordenvoz_options_rename_fecha_ordenvoz_creado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField()),
                ('mensaje', models.CharField(default='¡Es hora de tu medicamento!', max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('disparada_at', models.DateTimeField(blank=True, null=True)),
                ('entregada', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
