# Generated by Django 5.2.6 on 2025-10-20 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miappeva', '0003_alarma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronVoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando_original', models.CharField(max_length=100)),
                ('texto_reconocido', models.CharField(max_length=100)),
                ('similitud', models.FloatField(default=0.0)),
                ('aciertos', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('fecha_ultimo_uso', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
