# Generated by Django 5.2.6 on 2025-11-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miappeva', '0007_alarma_dias_alarma_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarma',
            name='dias',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
