# Generated by Django 6.0.1 on 2026-02-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miappeva', '0009_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
