# Generated by Django 6.0.1 on 2026-02-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miappeva', '0011_alter_pushsubscription_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatVoz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('audio_ruta', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('texto', 'texto'), ('audio', 'audio')], max_length=10)),
                ('duracion_segundos', models.IntegerField(blank=True, null=True)),
                ('escuchado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('enviado', 'enviado'), ('leido', 'leido'), ('fallido', 'fallido')], default='enviado', max_length=10)),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_voz',
                'managed': False,
            },
        ),
    ]
